### ISSUE TITLE
UnboundLocalError: local variable 'input_vector' referenced before assignment

### ISSUE THREAD

**Issue by meowd18** [MorganCThomas/SMILES-RNN#16]
In the model files (rnn.py, transformer.py and gated_transformer.py), there is a mistake on a line causing an error:
UnboundLocalError: local variable 'input_vector' referenced before assignment

I think
input_vector = input_vector.to(self.device)
should be
input_vectors = input_vectors.to(self.device)

**Comment by MorganCThomas** [comment]
Fixed the typo with latest commit d1b0cc57e2fe3eaf6cc6d1ffca1f714cc1d7b341
